# -*- coding: utf-8 -*-
"""Reto_Numpy_semana7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdKt27-z8ct29tap6JtxNRDgg-m3Wb-Z

1.	Crear un objeto de tipo ndarray, con números enteros entre 64 hasta 1024.

2.	Redimensionar a una matriz bidimensional que tenga las 1024 observaciones, pero que su dimensión tenga tanto el mismo número de filas como de columnas, con la finalidad de obtener una cuadrada.

3.	Crear una columna de datos aleatorios de 30 observaciones o registros, en la que se escojan dichos registros desde una lista de 10 nombres. Se debe repetir el proceso anterior para crear un set de números de cédulas aleatorio para cada uno de los nombres.

Lista=[‘Andres’,’Maria’,’Manuel’,’Daniel’,’Sarah’,’Cristian’,’Violetta’,’Lucia’,’Jackson’,’Jose’]

4.	Concatenar un nuevo vector con las observaciones de los nombres y cédulas.

5.	Mostrar la posición del número más grande de las cédulas generadas del vector creado en el punto 4. Se debe investigar Slicing notation en numpy.
"""

import numpy as np
a = np.arange(64,1025)
print(a)

a.reshape(31,31)

Lista=["Andres","Maria","Manuel","Daniel","Sarah","Cristian","Violetta","Lucia","Jackson","Jose"]
nombre = np.random.choice(Lista,size=30)
print(nombre)

cedula=np.random.randint(4251,99999,size=30)
print(cedula)

Identificacion=np.ma.concatenate(([nombre],[cedula]),axis=0)
Identificacion

Identificacion.argmax()